import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const body = await req.json().catch(() => ({}));
  return NextResponse.json({
    agentId: params.id,
    question: body.question ?? '',
    answer: 'Preview responses will be generated by the VM gateway in Prompt 4.12. This stub keeps the detail-page flow usable during frontend buildout.',
    limited: false,
  });
}
